deploymentName: product-service-deployment
serviceName: product-service
appLabel: product-service
appName: product-service

replicaCount: 1

image:
  repository: hiroki111/easycar-product-service
  tag: 1.0.0

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
rabbitmq_enabled: true
datasource_enabled: true
redis_enabled: true