# TODO: Move this to https://github.com/Hiroki111/java-microservice-config after migrating to Kubernetes
build:
  version: "3.0"

order-service:
  message: "order-service related dev APIs "
  contactDetails:
    name: "Carol"
    email: "carol@easycar.com"
  onCallSupport:
    - (111) 222-7777
    - (111) 222-8888