spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:Hiroki111/java-microservice-config.git"
          default-label: main
          timeout: 5 # i.e. 5 minutes
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "classpath:/config"

server:
  port: 8071
