global:
  configMapName: easycar-prod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  # NOTE: This isn't "rabbit"
  rabbitmqHost: rabbitmq
  rabbitmqPort: 5672
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  # NOTE: This isn't "redis"
  redisHost: redis-master
  redisPort: 6379
  datasourceUserName: postgres
  datasourcePassword: secret
  orderServiceDatasourceUrl: jdbc:postgresql://order-service-db:5432/order-service-db
  productServiceDatasourceUrl: jdbc:postgresql://product-service-db:5432/product-service-db
