kube-prometheus:
  prometheus:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "800m"
        memory: "1Gi"
    retention: "2h"
    scrapeInterval: "30s"

  alertmanager:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

  nodeExporter:
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
