deploymentName: order-service-deployment
serviceName: order-service
appLabel: order-service
appName: order-service

replicaCount: 1

image:
  repository: hiroki111/easycar-order-service
  tag: 2.0.0

containerPort: 8082

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

datasourceKey: ORDER_SERVICE_DATASOURCE_URL

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
rabbitmq_enabled: true
datasource_enabled: true
redis_enabled: false