server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

info:
  app:
    name: message
    description: "easycar message service"
    version: 2.2.0