server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

info:
  app:
    name: message
    description: "easycar message service"
    version: 2.1.0