server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # This "update" updates the schema if necessary and doesn't drop existing tables
      # Use it only on dev/test environment
      ddl-auto: update
    show-sql: true