server:
  port: 8081

spring:
  application:
    name: product-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  devtools:
    restart:
      enabled: false
  data:
    web:
      pageable:
        max-page-size: 10000
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product-service-db}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    function:
      definition: reserveProduct
    stream:
      bindings:
        reserveProduct-in-0:
          destination: reserve-product
          group: ${spring.application.name}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: product-service
    description: "easycar product service"
    version: 1.0.0

logging:
  level:
    com:
      easycar:
        product_service: DEBUG
    org:
      springframework:
        data:
          redis=DEBUG: