apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-db
  template:
    metadata:
      labels:
        app: order-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          # TODO: Organize these variables by ConfigMaps
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_DB
              value: "order-service-db"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-db
spec:
  selector:
    app: order-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
