apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: hiroki111/easycar-eurekaserver:1.0.0
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eurekaserver"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8070
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: ClusterIP
