loki:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 2h
